### ISSUE TITLE
How to launch

### ISSUE THREAD

**Issue by celikemir** [jetdillo/oakd_models#1]
after compiling the repo, Could not get successfully  launch with the following command

`roslaunch oakd_description description.launch`

so can you show example launch command to reach image and point cloud and mounting the camera any robot ?

**Comment by celikemir** [comment]
by the way there is no spawn launch 

 <include file="$(find oakd_gazebo)/launch/oakd_spawn.launch">

**Comment by jetdillo** [comment]
Hi, can you share  some diagnostics, like terminal output or a screenshot of what you tried so I can see what's going on when you're running it ? 
Thanks!

**Comment by jetdillo** [comment]
> by the way there is no spawn launch

Sorry about that, I'll try to track down the correct file. I've lost some data since I first uploaded this. 

This is a pretty standard spawning script though. It loads the model and then calls the spawn node inside `gazebo_ros`. 
Like this:
` 
    <node pkg="gazebo_ros" type="spawn_model" name="urdf_spawner" 
        args="-z 0.3
        -urdf
        -model curio
        -param robot_description"
        respawn="false" output="screen" />
`
Hope that helps in the short term.

**Comment by jetdillo** [comment]
Fixed a syntax error within the `oakd.urdf.xacro` file. Tested on the [Tenacity](https://github.com/jetdillo/tenacity_rover) repo as an example. Seems to work now.

**Comment by jetdillo** [comment]
Hi there, have you had a chance to test the fix(es) I pushed up earlier this week ? 
I'll close this if I don't hear back by next week.

**Comment by jetdillo** [comment]
Closing for lack of response from OP over the past couple weeks. 
Feel free to re-open if there's still a problem or if you can show what you tried and why it still doesn't work.
